### ISSUE TITLE
Response to OSCS & Murphy Security

### ISSUE THREAD

**Issue by Ristellise** [Ristellise/MiyafujiPosting#1]
So I decided to look into my inbox and found this email marked as spam.

![image](https://user-images.githubusercontent.com/7894419/213374177-b2c69007-2b05-4603-bc57-daf61df7221c.png)

Here is my reply in full plain text:

```
Good day OSCS & Murphy Security,

I have read your email in full and I would like to raise a couple of questions:

1. Why is this directed through an email and not via through a github issues page?
2. Why is the package targeted? I believe there is nothing of importance located in this repositary. (I have personally checked it myself and do not understand why I would need such a service in the first place)
3. Why in the world is the email itself not encrypted even though it is reported to be sent by sendcloud.io? Even though it is a security issue email, the email itself isn't secure?

I would like the responses to be prompt. 

Thank you.

Regards,
Shinon
```

I believe the relevant personel on github is @claire9910 as of now.

**Comment by claire9910** [comment]
@Ristellise Hello, thank you for receiving your reply,
We mainly focus on the security risks of using open source components in the project, and remind developers to pay attention to the relevant risks. The security detection report should be private, while the issues content is public. If you don't care or don't help, you can ignore it. We won't wake up again later.
We will pay more attention to the encryption of the message itself. Thank you for your suggestion.

**Comment by Ristellise** [comment]
> @Ristellise Hello, thank you for receiving your reply, We mainly focus on the security risks of using open source components in the project, and remind developers to pay attention to the relevant risks. The security detection report should be private, while the issues content is public. If you don't care or don't help, you can ignore it. We won't wake up again later. We will pay more attention to the encryption of the message itself. Thank you for your suggestion.

Hi. Thank you for the reply. I believe it is satisfactory.
